from setuptools import setup

setup(
    name='polykriging',
    version='0.3.2',
    description='A kriging package as a result of the course MEC 6310',
    url='https://github.com/shuds13/polykriging',
    author='Bin Yang',
    author_email='bin.yang@polymtl.ca',
    license='GPL',
    packages=['polykriging', 'polykriging.geometry',
              'polykriging.kriging', 'polykriging.mesh', 'polykriging.plot',
              'polykriging.stats', 'polykriging.thirdparty'],
    install_requires=['numpy>=0.5',
                      'matplotlib',
                      'sympy',
                      'tk',             #tkinter
                      'shapely',
                      'SciencePlots', 
                      'opencv-python',
                      'pyvista',
                      'meshio',
                      'scikit-learn',
                      'opencv-python',
                      ],

    classifiers=[
        'Development Status :: 1 - Planning',
        'Intended Audience :: Science/Research',
        'License :: OSI Approved :: BSD License',  
        'Operating System :: POSIX :: Linux',        
        'Programming Language :: Python :: 3.5',
        'Programming Language :: Python :: 3.7',
        'Programming Language :: Python :: 3.8',
        'Programming Language :: Python :: 3.9',
        'Programming Language :: Python :: 3.10',
        'Programming Language :: Python :: 3.11',
        'Programming Language :: Python :: 3.12',
    ],
)
